version: '3.3'
services:
  app:
    container_name: app
    build: .
    ports:
      - 9000:9000
      - 80:8080
    volumes:
      - .:/app
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./env/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./env/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./env/grafana/dashboard.json:/var/lib/grafana/dashboards/spring.json
    ports:
      - 3000:3000
    env_file:
      - ./env/grafana.env