server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health"
  endpoint:
    health:
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true
    prometheus:
      enabled: true
  server:
    port: 9000